1806 add functionality on customized open day & time filter
hackforla/food-oasis pull request #1946
Opened 2023-12-17 23:28 UTC by VirginiaWu11

https://github.com/hackforla/food-oasis/assets/79432798/7abc275f-36eb-42b3-87fa-97f8193ab8a9

On this branch, I have implemented the day/time advanced filter functionality on the filter panel & removed the "Days" filter button on the map.

2023-12-18 17:52 UTC, qiqicodes commented on client/src/helpers/index.js
> +// console.log(nextDate.toString());
Since there is `Example Usage` for this function, it would be nice to also provide the return value of the function.

2023-12-18 18:38 UTC, qiqicodes requested changes

2023-12-18 18:38 UTC, qiqicodes commented on client/src/hooks/useOrganizationBests.js
>          );
`neighborhoodId` currently doesn't exist on the `filters` object. We can remove this condition, and if we want to implement this in the future, we can revisit this.

2023-12-18 18:38 UTC, qiqicodes commented on client/src/helpers/index.js
> +  const dayInput = customizedOpenTimeFilter.day;
Nit: I'd recommend refactoring this to 
`const { day: dayInput, time: timeInput } = customizedOpenTimeFilter;`

the code is cleaner and more DRY 😄

2023-12-18 18:38 UTC, qiqicodes commented on client/src/hooks/useOrganizationBests.js
> +        filteredStakeholders = filteredStakeholders.filter((stakeholder) => {
We can abstract the inactive & temporary inactive filter to a reusable helper function, other functionalities may be able to consume this filter.

2023-12-18 23:05 UTC, VirginiaWu11 commented on client/src/components/FoodSeeker/SearchResults/StakeholderPreview/StakeholderPreview.js
> +    new Date()
make new Date easier to understand & check how often the new date is updated

2023-12-18 23:39 UTC, VirginiaWu11 commented on client/src/components/FoodSeeker/SearchResults/StakeholderPreview/StakeholderPreview.js
> +    new Date()
@qiqicodes new Date() is ran each time the StakeholderPreview is rendered.

2023-12-22 16:16 UTC, qiqicodes requested changes

2023-12-24 22:47 UTC, qiqicodes approved these changes
LGTM =]

2024-01-09 03:32 UTC, kurikurichan approved these changes
LGTM though we should test it on the dev site with Heroku's timezone difference!

2024-01-12 02:31 UTC, merged