Fix stakeholder preview getting cut off
hackforla/food-oasis pull request #2113
Opened 2024-04-10 02:23 UTC by hanapotski

2024-04-16 00:35 UTC, andyarensman requested changes
Double scroll bar is now showing

2024-04-30 17:47 UTC, andyarensman requested changes
The double scroll bar is gone, but the information is still being cut off for me:

![chrome_SCgmHTvgTw](https://github.com/hackforla/food-oasis/assets/86622025/f9cdc667-3c6a-4193-b9dd-3ec9702f0cc6)

2024-05-01 02:27 UTC, hanapotski commented
🤦‍♀️ will look into it more 🧐 I think we need to dynamically change the height of the list container

2024-05-15 11:44 UTC, 93Belen commented
I added the position of the Draggable component to the App State, and then use it to dynamically change the padding of the Stake Holder Details. If you guys test it in the Desktop with the screen as Mobile, the padding looks like is too much, but it works on the actual phone device. At least in mine :)
Also, I still have double scrolling in the phone, no in the Desktop as phone.

https://github.com/hackforla/food-oasis/assets/98275292/df758efc-07e9-4f71-aa99-d51949afea6c

2024-05-17 00:24 UTC, andyarensman commented on client/src/components/FoodSeeker/SearchResults/StakeholderDetails/StakeholderDetails.js
> +  console.log(position)
Leftover console.log

2024-05-17 20:25 UTC, 93Belen commented
@andyarensman I removed it, thank you! :)

2024-05-17 22:33 UTC, andyarensman approved these changes
LGTM. I  guess we can fix the phone double scroll in a separate issue? @hanapotski

2024-05-21 00:08 UTC, merged