Group pins when they bunch together
hackforla/food-oasis pull request #779
Opened 2020-12-01 05:13 UTC by carterharrison

Uses Mapbox's cluster functionality to group pins together. 
![Map](https://i.imgur.com/6viz2bo.png)

Fixes https://github.com/hackforla/food-oasis/issues/761

2020-12-01 17:28 UTC, bbovenzi commented
Thanks for taking this on Carter! This is a great start and will really help make our map work better. A few notes:

1. Critical: When clicking on a cluster, the individual pins aren't visible until I slightly zoom in manually. 
2. Performance: It's taking a while to rerender the map when clicking on clusters or zooming. I am happy to help work on that part.
3. Design: Let's update the colors of a cluster to match the blue we currently use in the app. The text will have to be white to match.
4. Code quality: Leaving a few nitpick comments in the files to stay consistent with best practices.

Feel free to chat here or on Slack and we can get this wrapped up!

2020-12-01 17:29 UTC, bbovenzi commented on client/src/components/Results/ResultsMap.js
> +      "#51bbd6",
No hard-coded colors. It would be best if the theme file is the only source of truth for hex or rgb colors.

2020-12-01 17:32 UTC, bbovenzi commented on client/src/components/Results/ResultsMap.js
> +    "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
Let's also refer to the main theme for fonts. Feel free to update the theme file as needed

2020-12-01 17:32 UTC, bbovenzi commented on client/src/components/Results/ResultsMap.js
> +  const shownStakeHolders = [];
should be `shownStakeholders` "stakeholder" is a single word so no need to camelCase it.

2020-12-01 17:33 UTC, bbovenzi commented on client/src/components/Results/ResultsMap.js
> +          if (err) {
Let's `console.error` here, just in case.

2020-12-08 18:04 UTC, entrotech commented on client/package.json
> +  "proxy": "https://foodoasis.la",
The proxy setting allows us to run both server and client locally. This change should not be merged.

2020-12-08 18:07 UTC, entrotech requested changes
Do not merge the change made to /client/package.json. Other than that, it looks good, but @bbovenzi  and Andrew Strauss will need to weigh in.

2020-12-08 18:33 UTC, carterharrison commented
@entrotech The PR is not ready to be merged. Although it works, some of the code is hacky, specifically the use of setTimeouts. I'll be able to resolve this sometime over the next couple days.

2021-01-06 02:37 UTC, bbovenzi commented
hey @carterharrison are you still handling this PR? I'm happy to wrap it up for you if you've become busy

2021-01-06 02:38 UTC, bbovenzi commented
hey @carterharrison are you still handling this PR? I'm happy to wrap it up for you if you've become busy

2021-01-20 02:31 UTC, merged